Gemfile.lock
app/controllers/bookings_controller.rb
app/controllers/cars_controller.rb
test/controllers/bookings_controller_test.rb
test/controllers/cars_controller_test.rb

Created controller for cars with index method and empty controller for bookings.

Controllers

---

Gemfile
Gemfile.lock
db/seeds.rb

added seeds

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_index.scss
app/views/cars/index.html.erb
config/routes.rb

Created the index.html.erb for the cars

---

app/controllers/cars_controller.rb
app/views/car/show.html.erb

I could't finished the view page so I will do tomorrow. Is this OK?

created method show and view show.html.erb

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_index.scss
app/views/cars/index.html.erb
config/routes.rb

Here is how it looks: 
Still have to fix some issue at the end of the page:

Fixed the cards and added the flex.

---

db/seeds.rb

finished seeds for all 3 models

finished seeding for all 3 models

---

Gemfile.lock
app/controllers/cars_controller.rb
app/views/cars/show.html.erb

created cars/show page

---

app/controllers/bookings_controller.rb
app/policies/booking_policy.rb
app/policies/car_policy.rb

Fixed bookings controller, able to make bookings now.

Fixed the bookings controller

---

app/controllers/bookings_controller.rb
app/controllers/cars_controller.rb
app/views/bookings/index.html.erb

added filter, name of the owner, and images of cars

added filter, name of the owner, and car image

---

app/views/bookings/index.html.erb

Booking page cont

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_image.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_table.scss
app/assets/stylesheets/components/_text.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/pages/_home.scss
app/views/bookings/_form.html.erb
app/views/bookings/index.html.erb
app/views/cars/index.html.erb
app/views/cars/new.html.erb
app/views/cars/show.html.erb
app/views/layouts/application.html.erb

Hey guys, changed colors and adjusted some layout stuff, hope its fine.

Color schema and some layout details

---

app/views/cars/index.html.erb
app/views/cars/show.html.erb

added icon for capacity and price

---

db/seeds.rb

added image to seeds

---

app/assets/stylesheets/components/_card.scss
app/views/bookings/index.html.erb

It seems fine as long as we don't make the browser small.

Inserted total price and organized infos

---

app/views/cars/_info_window.html.erb

created info window html file

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_icon.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_input.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_colors.scss
app/views/bookings/_form.html.erb
app/views/bookings/_garage.html.erb
app/views/bookings/index.html.erb
app/views/cars/index.html.erb
app/views/cars/new.html.erb
app/views/cars/show.html.erb
app/views/shared/_navbar.html.erb

Changed the update page to this:

Style showpage update

---

app/controllers/bookings_controller.rb
app/models/booking.rb
app/views/bookings/_form.html.erb

fixed booking scheduling issues

fixed booking errors

---

Gemfile
Gemfile.lock
app/controllers/cars_controller.rb
app/models/car.rb
app/views/cars/_info_window.html.erb
app/views/cars/index.html.erb
app/views/shared/_navbar.html.erb

We can search by car model, address, description or capacity now.

Added search

---

Gemfile
Gemfile.lock
app/controllers/cars_controller.rb
app/models/car.rb
app/views/cars/_info_window.html.erb
app/views/cars/index.html.erb
app/views/shared/_navbar.html.erb

Search by model(or description and category) and search by address working.

Add search by address

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_info_window.scss
app/views/cars/_info_window.html.erb

Added img into info window in map

---

app/controllers/bookings_controller.rb
app/controllers/cars_controller.rb
app/models/booking.rb
app/policies/booking_policy.rb
app/policies/car_policy.rb
app/views/bookings/_garage.html.erb
app/views/bookings/index.html.erb
config/routes.rb

added delete feature for both user and owner

---

app/models/car.rb
app/views/cars/new.html.erb

fixed negative integers input when creating cars

fixed negative integers input when creating cars

---

app/controllers/bookings_controller.rb
app/controllers/cars_controller.rb

fixed redirect after creating car and added a notice message

fixed redirect after creating car and added a notice message

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_image.scss
app/assets/stylesheets/components/_map.scss
app/assets/stylesheets/config/_colors.scss
app/views/bookings/index.html.erb
app/views/bookings/my_cars.html.erb
app/views/cars/my_cars.html.erb

Changed button colours for my cars and bookings. So it will look like a separate thing from the Booking requests.

Style my page

---

app/assets/stylesheets/components/_info_window.scss
app/views/cars/_info_window.html.erb

Added a link into info window and fixed text aline to left

---

app/assets/images/caret-down-solid.svg
app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_input.scss
app/views/bookings/_booking_card.html.erb
app/views/bookings/index.html.erb
app/views/bookings/my_cars.html.erb
app/views/cars/my_cars.html.erb

Fixed buttons

---

app/controllers/cars_controller.rb
app/views/cars/_info_window.html.erb

Adjusted the margin of the info window.

Fixed the margin of the map-info-window

---

app/assets/stylesheets/components/_info_window.scss

changeed closing button to white and made it bigger when hover

---

app/controllers/cars_controller.rb
app/views/cars/_info_window.html.erb

Adjusting card
